---
- name: Deploy application
  hosts: app

  tasks:
    - name: Install GIT
      become: true
      apt:
        name: git
        update_cache: yes
        state: present

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      notify: Restart puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit

  handlers:
    - name: Restart puma
      become: true
      service: name=puma state=restarted
