---
- name: Configure hosts & application deployment
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
    - name: Setup mongodb config file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      tags: db
