---
- name: Configure hosts & application deployment
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0

  tasks:
    - name: Setup mongodb config file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      tags: db
      notify: Restart mongod

    - name: Add unit file for Puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app
      notify: Reload puma

    - name: Enable puma
      become: true
      systemd: name=puma enabled=yes
      tags: app

  handlers:
    - name: Restart mongod
      become: true
      service: name=mongod state=restarted

    - name: Reload puma
      become: true
      service: name=puma state=restarted
